
shell_integration enabled no-cursor

enable_audio_bell no

font_family      SauceCodePro Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        24

foreground #101010
background #ffffff

url_color #5555ff

background_opacity 1

mouse_hide_wait -3.0
cursor_shape block
cursor_shape_unfocused hollow
cursor_text_color #000000
cursor #000000

