
[colors]
background = #dff4ff
background-alt = #cdeeff
foreground = #12324a

primary = #f2b6d4
secondary = #ffc8dd

blue = #8eb8ff
cyan = #a8e6ff
sky = #c6ecff

white = #12324a
gray = #8faac7
yellow = #f7c6dc

alert = #f2aac9
disabled = #9bb7cc

[bar/toph]
monitor = ${env:MONITOR}
width = 100%
height = 26
radius = 0

#background = ${colors.background}
foreground = ${colors.foreground}
background = ${colors.background}

line-size = 16
line-color = ${colors.background}

spacing = 0

padding-left = 0
padding-right = 1

module-margin = 1

tray-position = right

separator = ɞϊɞ
separator-foreground = ${colors.blue}

;font-0 = Hack Nerd Font Mono:size=10;3
font-0 = SauceCodePro Nerd Font:size=12;2
font-1 = "JetBrainsMono Nerd Font:size=12;2"

modules-center = date 
modules-left = xworkspaces spotify
modules-right = volume xkeyboard filesystem cpu battery memory wlan power 

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

tray-maxsize = 16
tray-scale = 1

bar-width = 10
bar-indicator = |
bar-indicator-font = 3
bar-indicator-foreground = #ff
bar-fill = ─
bar-fill-font = 3
bar-fill-foreground = #c9665e
bar-empty = ─
bar-empty-font = 3
bar-empty-foreground = #44

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

border-size = 0
border-color = ${colors.white}

bottom = true

margin-top = 0

[module/power]
type = custom/text
content = ⏻
click-left = poweroff

[module/systray]
type = internal/tray
tray-spacing = 8pt

[module/xkeyboard]
type = internal/xkeyboard

format-foreground = ${colors.white}

label-layout = %layout%

; List of indicators to ignore
blacklist-0 = num lock
blacklist-1 = scroll lock

[module/volume]
type = internal/pulseaudio
interval = 1


[module/xwindow]
type = internal/xwindow
label = %class%

format-foreground = ${colors.white}

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.primary}
label-active-foreground = ${colors.background}
label-active-underline= ${colors.lauve}
label-active-margin = 0px

label-occupied = %name%
label-occupied-background = ${colors.gray}
label-occupied-foreground = ${colors.background}
label-occupied-margin = 0px

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-margin = 0px

label-empty = %name%
label-empty-foreground = ${colors.gray}
label-empty-margin = 0px

label-active-padding   = 1
label-occupied-padding = 1
label-urgent-padding   = 1
label-empty-padding    = 1

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = space %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.mauve}

[module/wlan]
type = internal/wlan

[module/spotify]
type = custom/script
exec = playerctl --player=spotify metadata --format '{{ artist }} - {{ title }}'
interval = 1
format = <label>
; format-foreground = ${colors.black}
format-foreground = ${colors.white}

[module/memory]
type = internal/memory
interval = 2
format-prefix = "mem "
format-prefix-foreground = ${colors.white}
label = %percentage_used:2%%
format-foreground = ${colors.white}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "cpu "
format-prefix-foreground = ${colors.white}
label = %percentage:2%%
format-foreground = ${colors.white}

[module/date]
type = internal/date
interval = 1

date = %H:%M
date-alt = %Y-%m-%d %H:%M:%S

label = %date%
label-foreground = ${colors.white}
format-foreground = ${colors.white}


[module/custom_text]
type = custom/script
exec = ~/.config/polybar/random-word.sh
interval = 5

[settings]
screenchange-reload = true
pseudo-transparency = false

; vim:ft=dosini
